name: Build
on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'bugfix/**'
      - 'github/**'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    defaults:
        run:
          shell: cmd

    outputs:
      # accessible from other jobs as ${{needs.build.outputs.version}}
      version: ${{steps.version.outputs.version}}

    steps:
      - name: Version
        id: version
        shell: python
        run: |
          import os
          from datetime import datetime, timezone
          date = datetime.now(tz=timezone.utc)
          with open(os.getenv('GITHUB_OUTPUT'), "a") as fout:
            print(     f"version={date.year%100}.{date.month}.{date.day}.${{github.run_number}}")
            fout.write(f"version={date.year%100}.{date.month}.{date.day}.${{github.run_number}}\n")

      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace version in resource file
        run: python _set_version.py --version=${{steps.version.outputs.version}}

      - name: Build amd64-unicode
        run: |
          set PATH=C:\mingw64\bin;C:\msys64\usr\bin;%PATH%
          mingw32-make.exe ARCH=X64 CHAR=Unicode OUTDIR=build\Release-mingw-amd64-unicode -fMakefile.mingw clean all

      - name: Build x86-unicode
        run: |
          set PATH=C:\mingw32\bin;C:\msys64\usr\bin;%PATH%
          mingw32-make.exe ARCH=X86 CHAR=Unicode OUTDIR=build\Release-mingw-x86-unicode -fMakefile.mingw clean all

      - name: Build x86-ansi
        run: |
          set PATH=C:\mingw32\bin;C:\msys64\usr\bin;%PATH%
          mingw32-make.exe ARCH=X86 CHAR=ANSI OUTDIR=build\Release-mingw-x86-ansi -fMakefile.mingw clean all

      - name: Create package
        run: |
          rem | Collects all files in build\package
          _make_package.bat

      - name: Upload plugin package
        uses: actions/upload-artifact@v4
        with:
          name: NSxfer
          path: build/package/*
